name: cortex_exemplars_ingested
rules:
- expr: |
    sum by (cluster, namespace, job) (rate(cortex_ingester_ingested_exemplars_total[5m]))
  record: cluster_namespace_job:cortex_ingester_ingested_exemplars:rate5m