name: cortex_ingester_rules
rules:
- expr: |
    sum by(cluster, namespace, pod) (rate(cortex_ingester_ingested_samples_total[1m]))
  record: cluster_namespace_pod:cortex_ingester_ingested_samples_total:rate1m
