name: cortex_exemplars_appended
rules:
- expr: |
    sum by (cluster, namespace, job) (rate(cortex_ingester_tsdb_exemplar_exemplars_appended_total[5m]))
  record: cluster_namespace_job:cortex_ingester_tsdb_exemplar_exemplars_appended:rate5m