  name: cortex_received_samples
  rules:
  - expr: |
      sum by (cluster, namespace, job) (rate(cortex_distributor_received_samples_total[5m]))
    record: cluster_namespace_job:cortex_distributor_received_samples:rate5m