
target: all,alertmanager

limits:
  accept_ha_samples: true

distributor:
  shard_by_all_labels: true
  pool:
    health_check_ingesters: true
  ha_tracker:
    enable_ha_tracker: true
    kvstore:
      store: consul
      consul:
        host: consul:8500

ingester:
  lifecycler:
    ring:
      kvstore:
        store: memberlist

memberlist:
  join_members: [cortex-1, cortex-2]

querier:
  at_modifier_enabled: true

store_gateway:
  sharding_enabled: true
  sharding_ring:
    replication_factor: 1
    kvstore:
      store: memberlist

blocks_storage:
  backend: s3
  tsdb:
    dir: /data/cortex-tsdb-ingester

  bucket_store:
    sync_dir: /data/cortex-tsdb-querier

  s3:
    endpoint:          minio:9000
    bucket_name:       cortex-blocks
    access_key_id:     cortex
    secret_access_key: supersecret
    insecure:          true

storage:
  engine: blocks

compactor:
  data_dir: /data/cortex-compactor

ruler:
  enable_api: true
  enable_sharding: true
  poll_interval: 2s
  ring:
    kvstore:
      store: memberlist
  alertmanager_url: http://load-balancer
  rule_path: /data/rules

ruler_storage:
  backend: s3
  s3:
    bucket_name:       cortex-rules
    endpoint:          minio:9000
    access_key_id:     cortex
    secret_access_key: supersecret
    insecure: true

alertmanager:
  data_dir: /data/alertmanager
  sharding_enabled: true
  sharding_ring:
    kvstore:
      store: memberlist
  enable_api: true
  external_url: http://localhost:80/alertmanager
  cluster:
    peers: 'cortex-1,cortex-2'

alertmanager_storage:
  backend: s3
  s3:
    bucket_name:       cortex-alertmanagers
    endpoint:          minio:9000
    access_key_id:     cortex
    secret_access_key: supersecret
    insecure: true

runtime_config:
  file: /cortex/config/runtime.yaml
